Fixed hot reload fatal crash
Caused by Buildings --> BuildingPatch.CondensedDrawInMenu -> switch -> Mill draw logic.

Error capture:
Fatal error. Internal CRL error.

Logged error:
[15:39:37 ERROR Alternative Textures] This mod failed in the Input.ButtonReleased event. Technical details:
BadImageFormatException: Bad binary signature. (0x80131192)
   at AlternativeTextures.AlternativeTextures._ButtonReleased
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101