Squashed and merged SDV v1.6 alpha changes
commit 0d7c6d829fdf5530dae9b9732e5e321c2eadd02a
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Tue Mar 19 13:45:34 2024 -0500

    Added handling for Game1.isDarkOut change

commit f4b4b4ea4d302a5850e4ceb9c63de60ab26a5d41
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sat Mar 9 16:14:13 2024 -0600

    v7.0.0-alpha.15 released

commit 2d40b8b1b8db477cc719ed1b92d170dd2a4fd3f7
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sat Mar 9 16:12:19 2024 -0600

    Added handling for old cabin ItemName values

commit cfeaa5e893b9f8bbcd27fcb9d5725f171fc45fec
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sat Mar 9 16:11:54 2024 -0600

    Converted AlternativeTextureModel.Type from string to TextureType

commit bdaeb9c899df2aa731c57298c83c6f033a822ea3
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Wed Mar 6 14:16:41 2024 -0600

    v7.0.0-alpha.14 released

commit c5f443d457a7f6b8197f6218ef06201d494bed94
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Tue Mar 5 22:34:26 2024 -0600

    Minor code cleanup

commit 3c06de9b84bda54791d00daa7754dc303cfbf337
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Tue Mar 5 22:34:11 2024 -0600

    Fixed disposed texture issue for alternative textures

commit f3f4730ff6dc91be2c5d60b08e00d274fb3eb453
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Tue Mar 5 21:47:39 2024 -0600

    Fixed disposed texture issue for tools

commit 880a69380619b6eb69706edcf6aa71b83ae6c096
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Mon Mar 4 00:35:08 2024 -0600

    v7.0.0-alpha.13 released

commit 9898249a55394a7a6981a274515c0b8b910bf99f
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Mon Mar 4 00:34:58 2024 -0600

    Minor code cleanup

commit c4b7a4dca1f911040bce9cb6c2639f985b927ee0
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Mon Mar 4 00:34:43 2024 -0600

    Fixed erroneous double space

commit 1123e3e449bf00249b7fc325e36289af6e939c6b
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Mon Mar 4 00:34:01 2024 -0600

    Added example usage of CollectiveIds

commit 1aeb183fe2a0dbcf0047e3321001f6993381efc8
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Mon Mar 4 00:33:52 2024 -0600

    Implemented AlternativeTextureModel.CollectiveIds

commit 8e8d8601366d303cb6693f85653e816ba8d243f0
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Mar 3 23:36:01 2024 -0600

    Added example usage of ItemId

commit 19d601f6e2fc45e4d65074e643b06b322ca5eae2
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Mar 3 23:35:47 2024 -0600

    Implemented AlternativeTextureModel.ItemId

commit 90b649153384306b5cbd76232add78d1874270e2
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Mar 3 16:45:15 2024 -0600

    Removed obsolete ID-based methods / properties

commit 880da7377a339126ea9154500be5a7a5d5782e8e
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Mar 3 16:44:05 2024 -0600

    Temporary fix to prevent crash when textures are patched via Content Patcher

    Need to look into root cause on Content Patcher side

commit 519da01867d140577a98de5e27402412eb3159e7
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Mar 3 16:36:23 2024 -0600

    Removed unused TextureManager parameter

commit 9b8234e3f5fb479a90ded5de6cc3b0468a468cbe
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sat Mar 2 12:08:01 2024 -0600

    v7.0.0-alpha.12 released

commit d2bf724278b6e7ed7c88903edd341b382fadb58d
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sat Mar 2 12:05:33 2024 -0600

    Fixed fence gates being handled incorrectly via GetObjectName

commit 5dec9ee12bff73e19ef1dd50e29ba212eec65b9a
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Fri Mar 1 21:53:11 2024 -0600

    v7.0.0-alpha.11 released

commit b83108008052caeaa13f84d6994767d213a96cc6
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sat Feb 24 17:06:27 2024 -0600

    Handled Fence.performObjectDropInAction change

commit 35a1fc277f03f23a5e46748078a8462351cdb18b
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Mon Jan 22 15:27:51 2024 -0600

    v7.0.0-alpha.10 released

    Recompiled against latest SDV alpha version.

commit addbee65adbf4e5e95c31bb24e24ff88a565aea3
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Mon Jan 8 14:41:51 2024 -0600

    v7.0.0-alpha.9 released

commit 620578c3fecb368bec5cff9f96db32bbcdaba05d
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Mon Jan 8 14:41:31 2024 -0600

    Handled ResourceClump constructor change

commit 9d2c3676b94d180a639a5624704233b6501296ee
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Mon Jan 8 14:41:22 2024 -0600

    Handled ID to Id format change

commit 67ad1cf93e83bb00baba5e5367861f414f2239a3
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Tue Dec 5 18:05:51 2023 -0600

    v7.0.0-alpha.8 released

    Updated to handle changes to StardewValley.Internal.ItemQueryResolver.

    #53

commit 7ca6838fc4ed5275add700c2a3c7719b06fceda9
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Dec 3 17:28:12 2023 -0600

    v7.0.0-alpha.7 released

    #53

commit d26cbfa08f04169264977354e3365444185455f2
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Dec 3 17:28:06 2023 -0600

    Minor code cleanup

commit 5dcb69d68d1057372f801c8073f96e2a99ed1666
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Dec 3 17:27:33 2023 -0600

    Added example usage of AnimationModel.FrameType

commit 5cb5f625622d1c4c9de261e5c19dfb5efa29a566
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Dec 3 17:27:22 2023 -0600

    Implemented AnimationModel.FrameType for custom animation handling of machines

commit 7949a341a9c3da2c5a53bafc71a441441fe45afb
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Tue Nov 21 18:01:01 2023 -0600

    v7.0.0-alpha.6 released

    #53

commit 541de75673ecca584d4ccddf1f46cd870a697dc1
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Tue Nov 21 17:57:43 2023 -0600

    Handled outdated usage of LoadBase

    #53

commit 77b4bd3fbe1fc499455f9d413b1db48fe31a8ddf
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sat Nov 18 19:54:49 2023 -0600

    v7.0.0-alpha.5 released

commit b42a5e76420e4c9e51032c374a03b8ef10ce785a
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sat Nov 18 19:54:42 2023 -0600

    Removed obsolete Solid Foundations patch

commit f3b94b3898f6d8a13f55b89597131796c158844b
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Nov 12 00:04:07 2023 -0600

    v7.0.0-alpha.4

    #53

commit 57a67e35c111f20349b15c2c34d42bf2d99f1891
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Nov 12 00:03:58 2023 -0600

    Implemented actual fix for crash on load due to FruitTree patch

    #53

commit 8513d20fe3caaf5c5dc86b98297c132033685efa
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sat Nov 11 22:50:06 2023 -0600

    Revert "Implemented potential fix for crash on load due to FruitTree patch"

    This reverts commit ac5c4260d9039abf505b4bc9e6db9882154e5a19.

commit e42766bf95728049ff3a4395d4b6b5288ba8df1f
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 9 20:10:36 2023 -0600

    v7.0.0-alpha.3 released

    #53

commit 14cdf4cd639dd899165ad843844d48d5f4784fdb
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 9 20:10:15 2023 -0600

    Updated MinimumApiVersion

    #53

commit ac5c4260d9039abf505b4bc9e6db9882154e5a19
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 9 20:09:44 2023 -0600

    Implemented potential fix for crash on load due to FruitTree patch

    #53

commit ed370b4e8b87b063c5bcf633d7d51db1dcdc7f2b
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Fri Nov 3 19:45:21 2023 -0500

    v7.0.0-alpha.2 released

    #53

commit 15c4719d8b90e6518a88df8af48e36e3d3c84a96
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Fri Nov 3 19:45:12 2023 -0500

    Removed unintended shadows appearing for flooring textures

commit 17a2437c0c8e7dc9615d2f80ba69daa5ec8fd2ab
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 2 17:36:12 2023 -0500

    v7.0.0-alpha.1 released

commit 9a32fb13ac25829b49c5a5475f7e8c9866b97f28
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 2 17:26:33 2023 -0500

    Set the randomization default config to false for flooring, furniture, objects and buildings

commit 25192d4bf32501d76e7d9f9257744cf2e3276810
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 2 17:19:10 2023 -0500

    Implemented AlternativeTextureModel.IgnoreBuildingColorMask

    #53

commit f8bada923a04711de6cd6ef7269d41d033a10368
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 2 16:15:42 2023 -0500

    Attempt at simplifying building retexturing

    #53

commit 7893e05856de227c3f6c4371e4ab1782391fd885
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 2 12:05:28 2023 -0500

    Fixed crashed due to invalid data dictionary use

commit ebd788b6d5327cce41ab51b9c27cc69f7cb06946
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 2 10:18:41 2023 -0500

    Fixed vanilla house reverting to default in the paint menu

    #53

commit 066d3032cec8e1788e3e6f072447165f7ffb6b3e
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 2 10:18:22 2023 -0500

    Fixed houses recolors not appearing in the paint menu

    #53

commit a12d81ce7255adf3e856037599e5ffddf5594c0f
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 2 09:10:49 2023 -0500

    Fixed wallpaper and flooring not appearing once applied

    #53

commit 52dc96884040a6994f7790def94f7a9d8868ea34
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 2 08:31:32 2023 -0500

    Minor code cleanup

commit 21501de98818741e5503109b1d674e7c0438c892
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Thu Nov 2 08:30:28 2023 -0500

    Working mailbox retexturing

    #53

commit b8233ecc20a404e29a69628b46cda454f40b15a2
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Wed Nov 1 20:12:04 2023 -0500

    Working house retexturing

    #53

commit 4e0c3fc8815d1f9f2e767a70771df89fdefaba79
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Wed Nov 1 16:27:18 2023 -0500

    Fixed hot reload fatal crash

    Caused by Buildings --> BuildingPatch.CondensedDrawInMenu -> switch -> Mill draw logic.

    Error capture:
    Fatal error. Internal CRL error.

    Logged error:
    [15:39:37 ERROR Alternative Textures] This mod failed in the Input.ButtonReleased event. Technical details:
    BadImageFormatException: Bad binary signature. (0x80131192)
       at AlternativeTextures.AlternativeTextures._ButtonReleased
       at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

commit b6be1665443090b1fb8600779de486e29397720b
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Wed Nov 1 14:13:48 2023 -0500

    Somewhat working farm house in paint bucket menu

commit e0016ddacedfcc2c5605c072c7c87fa479429fd4
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Wed Nov 1 11:34:37 2023 -0500

    Removed unused JA API

commit f4810c7a3f9939b37229596a9e6da726f63412d8
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Wed Nov 1 11:33:20 2023 -0500

    Somewhat fixed farmhouses, mailboxes no longer work

commit 917ab218f5930df02aa85abe96ca4ce892330e06
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Wed Nov 1 10:02:17 2023 -0500

    Fixed season casing check

commit 35f92602919d7b85f22c027339e5538f8ea9bded
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Tue Oct 31 16:26:37 2023 -0500

    Resolved compiler errors from version migration

    #53

commit e30a7f2257cd5e0fbf5dd70126b8f45aeca5c8a8
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Mon Oct 30 15:49:16 2023 -0500

    Fixed paint tools not being available at Robin's shop

    #53

commit 7500d6e54b02da2852ac8ebd924b7fec871f3b8b
Author: Floogen <31755155+Floogen@users.noreply.github.com>
Date:   Sun Oct 29 17:25:42 2023 -0500

    Initial project migration to SDV v1.6

    #53